### ISSUE TITLE
Buttons do not work on servers due to error

### ISSUE THREAD

**Issue by borisliao** [borisliao/mbox#47]
**Describe the bug**
Buttons are not watched by the bot anywhere when there was a ssl error in any other server.

**To Reproduce**
1. Play songs
2. Sometimes on disconnect, the bot internally gets a ssl error
3. Play a song on another server
4. See that buttons do not work anymore

**Expected behavior**
Buttons to respond and be watched

**Additional context**
Logs of suspected case that disables all buttons in all servers.
> 2021-05-06 23:49:30,810 [ERROR] SSL error in data received
> protocol: <asyncio.sslproto.SSLProtocol object at 0x72ebc730>
> transport: <_SelectorSocketTransport fd=13 read=polling write=<idle, bufsize=0>>
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
>     ssldata, appdata = self._sslpipe.feed_ssldata(data)
>   File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
>     self._sslobj.unwrap()
>   File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
>     return self._sslobj.shutdown()
> ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
> 2021-05-06 23:49:31,311 [ERROR] Error when finished playing: 
> Traceback (most recent call last):
>   File "/home/pi/.local/lib/python3.7/site-packages/discord/player.py", line 603, in run
>     self._do_run()
>   File "/home/pi/.local/lib/python3.7/site-packages/discord/player.py", line 590, in _do_run
>     data = self.source.read()
>   File "/home/pi/mbox/src/music/element/MusicSource.py", line 87, in read
>     ret = self.original.read()
>   File "/home/pi/.local/lib/python3.7/site-packages/discord/player.py", line 228, in read
>     ret = self._stdout.read(OpusEncoder.FRAME_SIZE)
> AttributeError: 'NoneType' object has no attribute 'read'
> 2021-05-06 23:49:31,312 [ERROR] Registering button 🗑️failed. Message already registered.
> 2021-05-06 23:49:31,316 [ERROR] Registering button ⏮️failed. Message already registered.
> 2021-05-06 23:49:31,317 [ERROR] Registering button ⏯️failed. Message already registered.
> 2021-05-06 23:49:31,318 [ERROR] Registering button ⏭️failed. Message already registered.
> 2021-05-06 23:49:31,319 [ERROR] Registering button 🔉failed. Message already registered.
> 2021-05-06 23:49:31,320 [ERROR] Registering button 🔊failed. Message already registered.
> 2021-05-06 23:49:31,320 [ERROR] Registering button 💬failed. Message already registered.

What is suspected is that there might be some button combination that is causing this error.
_Nevertheless, the buttons handler events must get removed regardless of exception._

**Comment by borisliao** [comment]
When discord.py doesn't catch that it has been disconnected forcefully, it leaves the buttons on the gui, and can't reconnect,
```
2021-05-16 23:06:55,359 [INFO] Preparing to terminate ffmpeg process 4744.
2021-05-16 23:06:55,359 [INFO] ffmpeg process 4744 has not terminated. Waiting to terminate...
2021-05-16 23:06:55,363 [INFO] ffmpeg process 4744 should have terminated with a return code of 1.
2021-05-16 23:07:20,410 [INFO] Received play from 3upman
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\bliao\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\bliao\Desktop\mbox/main.py", line 243, in on_message
    await src.parser.play_ytid('JwmGruvGt_I', mbox_ctx)
  File "C:\Users\bliao\Desktop\mbox\src\parser.py", line 71, in play_ytid
    if(voice_channel): await context.profile.player.connect(voice_channel)
  File "C:\Users\bliao\Desktop\mbox\src\music\player.py", line 209, in connect
    self.connected_client = await channel.connect()
  File "C:\Users\bliao\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\abc.py", line 1147, in connect
    raise ClientException('Already connected to a voice channel.')
discord.errors.ClientException: Already connected to a voice channel.
2021-05-16 23:07:35,695 [INFO] No more music to play. Stopping...
2021-05-16 23:07:55,106 [INFO] The voice handshake is being terminated for Channel ID 843682711603642368 (Guild ID 761679294799020053)
2021-05-16 23:07:55,107 [INFO] Reconnect was unsuccessful, disconnecting from voice normally...
```

**Comment by borisliao** [comment]
A solution could be that the buttons get removed if there was a error registering the event.

**Comment by borisliao** [comment]
Duplicate issue #72
